### ISSUE TITLE
Application crashes if scanned assemblies are duplicated

### ISSUE THREAD

**Issue by HEskandari** [Caliburn-Micro/Caliburn.Micro#737]
We have a plugin model that discovers view/viewmodels from external assemblies. If by mistake the assemblies are copied twice (to different discovery locations), the application would blow up with the following stack trace.

The `SelectedAssemblies()` method uses assemblies where as underlying cache which is the cause of the problem uses the Type name as the key.

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Caliburn.Micro.EnumerableExtensions.Apply[T](IEnumerable`1 enumerable, Action`1 action)
   at Caliburn.Micro.AssemblySourceCache.<>c.<Install>b__3_0(Object s, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Caliburn.Micro.BindableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Caliburn.Micro.BindableCollection`1.OnUIThread(Action action)
   at Caliburn.Micro.BootstrapperBase.StartRuntime()
   at Caliburn.Micro.BootstrapperBase.Initialize()
   at ServiceInsight.Startup.AppBootstrapper..ctor() in /_/src/ServiceInsight/Startup/AppBootstrapper.cs:line 41
```

A simple fix would be to not add duplicate items to the cache if they already exist.

**Comment by KasperSK** [comment]
@HEskandari Which version of Caliburn are you using? 
I believe that this was fixed in the 4.0 release candidate.

**Comment by HEskandari** [comment]
@KasperSK I was on the latest public release (not the RC). I can try the latest RC 4 and confirm if it is fixed.

**Comment by KasperSK** [comment]
@HEskandari Have you tried this with the new release of Caliburn.Micro?

**Comment by HEskandari** [comment]
I had an attempt to verify this on our codebase. It won't be possible to test it directly as moving to v4 will be non-trivial for us (all the new async APIs).

Just by looking at [the code](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform.Core/AssemblySource.cs#L101), I think this is not fixed. I'll see if I can send a test/PR soon.

**Comment by HEskandari** [comment]
@KasperSK Raised a PR with a failing test and the fix.

**Comment by vb2ae** [comment]
@HEskandari thanks for the PR
